### PR TITLE
shorten some line lengths

### PR DESCRIPTION
**Pull request by zachlysobey**
I have a strange compulsion to try to keep line-lengths short. How would you feel about some PRs like this?

### CODE REVIEW

**Comment by alexandernst** [comment]
I like it! But please make jshint happy again before I can merge it. https://travis-ci.org/alexandernst/angular-multi-select/builds/84115376

**Comment by zachlysobey** [comment]
Ah, didn't realize you had JSHint going. I'll try to take a stab later. Thanks for the quick reply.

If I end up using this plugin (jury's still out on how I approach my situation) I may try to commit some other stuff too. Are you trying to actively work on this project still? Any hope of merging back with isteven's? I prefer your code base b/c it seems significantly less sloppy ;-)

**Comment by alexandernst** [comment]
I do want to work on it, it's just that I don't have time right now. I will get to it, eventually, so don't worry, I'll end up fixing all the issues I created ;)
Anyways, I always review PRs in less than a day, so you can be sure I'll check (and merge if good) any PRs you throw at this project.

There are no plans merging this back with isteven's code. The guy doesn't seem to understand basic coding rules, how angular works, how git works nor pretty much how to make his code clean and usable.
I tried pushing a few patches, but he would copy&paste them in the code instead of accepting the PRs, and beyond that, his code is just beyond repair (which is why I just rewrote the entire thing).

**Comment by zachlysobey** [comment]
Not super skilled at git/github/PR stuff. Probably should've squashed these commits, and made this a bit nicer, but not quite sure how. What you think?

Also, I'm fairly confident my refactor here was "good", but am putting faith in the unit test suite without actually reviewing if this segment of code is covered.

**Comment by zachlysobey** [comment]
Hmmm... and I just saw that you already had, then [removed bower_components form `.gitignore`](https://github.com/alexandernst/angular-multi-select/commit/0cdfe6f4edc975a3ef1889d8586eee91075b6b69#diff-a084b794bc0759e7a6b77810e01874f2). It looks like bower was re-added, and maybe you just missed it in the gitignore?

**Comment by zachlysobey** [comment]
I discovered that my newly extracted function is actually the only _named_ function in this whole js file. Any reason why everything (even just little helper functions) is registered on `$scope`, or is that just a relic of isteven's code?

``` javascript
function hasHelperElementOption(helperElement) {
    return attrs.helperElements.search(new RegExp("\\b" + helperElement + "\\b")) !== -1;
}
```

**Comment by zachlysobey** [comment]
lol. disregard that ^^^. Safe to say however that the test suite doesn't adequately prevent subtle bugs here...

**Comment by alexandernst** [comment]
Everything looks perfect. The only thing that I'd change is the named vs scoped functions. Declaring functions as scoped let's angular manage/release them when required. Aside, from that, this is ready to merge.

**Comment by alexandernst** [comment]
Oh, also, please use `_` in front of the name, just to make it clear that the function is private, like here: https://github.com/alexandernst/angular-multi-select/blob/master/src/angular-multi-select.js#L1183

**Comment by zachlysobey** [comment]
done. 
However, that seems a bit suspicious to me, especially since it seems the prevailing wisdom in angular-land nowadays is to avoid `$scope` all-together, except when using `$watch`,`$emit`, `$apply`, etc... Not to mention thats really cluttering the scope with lots of stuff that is essential global to your directive. Do you have a reference to somewhere that suggests this style?

**Comment by alexandernst** [comment]
Hmmm.... maybe what I'm saying doesn't apply anymore to newer versions of Angular? Let me check that in SO ([here](http://stackoverflow.com/questions/33002007/using-named-functions-or-putting-them-inside-scope))

**Comment by zachlysobey** [comment]
upvoted ;-)

**Comment by alexandernst** [comment]
@zachlysobey So, turns out there are no performance gains for doing it the other way around, but it is true that the scope gets polluted and makes debugging harder. I'll create an issue to remind me I need to refactor all the functions that aren't used from the templates. ;)

Thank you for noticing that!

**Comment by zachlysobey** [comment]
@alexandernst sure thing. That'll be some good low hanging fruit for me to get some more PR's in too... trying to get my GitHub OSS participation up ;-)

**Comment by alexandernst** [comment]
@zachlysobey You're free to follow https://github.com/alexandernst/angular-multi-select/issues/47 I'll give you tips if/when you're ready to work on it!

**Pull request merged**
