### PR TITLE
Just a small catch... formatting

### PR DESCRIPTION
**Pull request by allanwsilva**

### CODE REVIEW

**Comment by alexandernst** [comment]
`input` is a void element, thus it doesn't have a closing tag.

**Comment by allanwsilva** [comment]
I know it is void, just to be HTML5 compliant... anyway, up to you merge it
or not.

Em ter, 14 de jun de 2016 às 16:32, Alexander Nestorov <
notifications@github.com> escreveu:

**Comment by alexandernst** [comment]
I'm not sure what do you mean with HTML5 compliant. https://www.w3.org/TR/html5/syntax.html#void-elements specs from HTML5 say that `input` is void, thus it shouldn't have a closing tag. Maybe I'm missing something?

**Comment by allanwsilva** [comment]
You're right, please delete this pull request.

Sorry about that,

Em ter, 14 de jun de 2016 às 17:29, Alexander Nestorov <
notifications@github.com> escreveu:

**Pull request closed without merging**
