### PR TITLE
Added toggleChildren option (default is true to maintain current behavior)

### PR DESCRIPTION
**Pull request by corydorning**
per the issue i filed here...

https://github.com/alexandernst/angular-multi-select/issues/55

### CODE REVIEW

**Comment by alexandernst** [comment]
This looks cool!
One more thing, can you add a line or two in the docs? (docs branch)

**Comment by corydorning** [comment]
Will do when I get into work tomorrow

**Comment by alexandernst** [comment]
Ok, as soon as you're done with that I'll merge

**Comment by corydorning** [comment]
gh-pages or dev branch? don't see a docs branch

**Comment by alexandernst** [comment]
Ah, indeed, gh-pages, sorry

**Comment by corydorning** [comment]
That's what I figured. Done.

**Comment by alexandernst** [comment]
Thank you for the PR!

**Pull request merged**
