### PR TITLE
fixes to bower packaging and build

### PR DESCRIPTION
**Pull request by jtbdevelopment**
bower packaging #43

### CODE REVIEW

**Comment by alexandernst** [comment]
The only thing I don't like in this PR is that you

a) removed the `dependencies` section in the `package.json` file
b) changed the indent
c) you're making `bower` mandatory (using the `scripts`) and there is no need for it. The `dependencies` section works just fine. There is a reason I upload this package to npm and bower and that is to not force people to use `npm` or `bower`.

Can you please fix those 3 little things?

One more thing, can you revert this https://github.com/alexandernst/angular-multi-select/commit/bb4e8e741213cdeebc813c9427aa7c42c5cccb7b to make Travis CI happy again?

**Comment by jtbdevelopment** [comment]
b)    will see if I can resurface it to old indent

Re:  a) c)
I'm not sure why you are publishing to bower if you don't like bower or don't intend to follow the standards of bower.  It works really nicely when done correctly

In order for the dependency chain to work out, the dependencies need to be in bower.json so when someone does bower install X it also picks up the needed dependencies automatically.  (as well as modify your index.html file to include the needed files with a correctly defined main)

You _could_ repeat yourself and put them in both places - but this is bad practice and can lead to errors/mistakes.  Again - not sure why you are trying to publish to bower at all if you don't want a proper bower package.  Or even what your complaint with bower is since it is the standard for client side packaging.

**Comment by alexandernst** [comment]
No, I'm fine with following bower standards. Really, your PR looks fine. I just don't want to force people that are using only npm to use bower too (which is what you're doing by putting the `bower install` in the `scripts` section of the `package.json` file).

There is no reason in forcing bower commands when npm can handle the same job exactly the same way.

So, to sum up: I want to keep bower and npm install paths completely separate and let each developer choose the tools he/she wants to use.

**Comment by jtbdevelopment** [comment]
One - the travis revert  doesn't seem to do much - i think you'll have to look at travis setup

"So, to sum up: I want to keep bower and npm install paths completely separate and let each developer choose the tools he/she wants to use."
Again - to have a proper bower package would require you to dupe these dependencies in both packages.json and bower.json which is a recipe for problems in the future.

I'm not putting my name on commit like that.  

Who doesn't use both as a serious client side javascript dev?
and my goodness - bower takes up no virtually no space or time - we've wasted more time arguing over bower

take it or don't take the pull - i don't care anymore

**Pull request merged**
