### PR TITLE
Use non default interpolation symbols

### PR DESCRIPTION
**Pull request by alazaro**
Allow the use of non default interpolation symbols by configuring `$interpolateProvider` (https://docs.angularjs.org/api/ng/provider/$interpolateProvider)

### CODE REVIEW

**Comment by alexandernst** [comment]
Nice addition. This was shortly available a few versions ago, but I had to remove it because of buggy behavior with nested views. Let's merge this and see how it behaves.

Just one thing, can you add a line or two in the docs? (gh-pages branch)

**Comment by alexandernst** [comment]
@alazaro ping

**Comment by alazaro** [comment]
@alexandernst done :)
https://github.com/alexandernst/angular-multi-select/pull/64

**Comment by alexandernst** [comment]
Thank you very much ;)

**Pull request merged**
